### ISSUE TITLE
timed out waiting to send media frame

### ISSUE THREAD

**Issue by MicheleCardamone** [QuantumEntangledAndy/neolink#117]
Hi!
Neolink version 0.5.14
after a few hours of correct functioning, gives the following errors and the video stream does not restore until I close and reopen neolink.
I am attaching my config.toml file

[config.txt](https://github.com/QuantumEntangledAndy/neolink/files/12117781/config.txt)
![neolink 0 5 14](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/741a5d4c-34fc-4720-9dc6-2f141353af69)

**Comment by 0ry0n** [comment]
I have the same problem.

**Comment by MicheleCardamone** [comment]
> I have the same problem.

For now i'm using 0.5.11

**Comment by apedance** [comment]
Same problem here.

**Comment by rcastro01** [comment]
Same problem here on all my cellular cameras

**Comment by QuantumEntangledAndy** [comment]
For those that say you have the same issue can you confirm it is for `Timed out waiting to send Media Frame` there are a few different places where `Deadline has elapsed` can happen so the additional context is there to help pin down which one is the real issue

**Comment by QuantumEntangledAndy** [comment]
The issue from what I can see is async exhaustion. Something is not yielding the thread so that means that the buffers aren't being processed and the whole system locks up until timeout happens.

Unless I can replicate and run the tokio-console to visualise locking threads then I won't be able to debug this very well. Is there anything about your setups that might help me duplicate

**Comment by kevin-david** [comment]
I am seeing this same error during login to 1/2 of my cameras: 

```
[2023-08-04T13:44:46Z INFO  neolink::mqtt::event_cam] backyard_camera: Connecting to camera at Address: 192.168.1.194
[2023-08-04T13:44:46Z INFO  neolink_core::bc_protocol] backyard_camera: Trying TCP discovery
[2023-08-04T13:44:46Z INFO  neolink_core::bc_protocol] backyard_camera: TCP Discovery success at 192.168.1.194:9000
[2023-08-04T13:44:46Z INFO  neolink::mqtt::event_cam] backyard_camera: Logging in
[2023-08-04T13:44:51Z WARN  neolink::mqtt::event_cam] Camera thread error: Failed to login to the camera
    
    Caused by:
        deadline has elapsed. Restarting...
[2023-08-04T13:47:02Z INFO  neolink::mqtt::event_cam] backyard_camera: Connecting to camera at Address: 192.168.1.194
[2023-08-04T13:47:02Z INFO  neolink_core::bc_protocol] backyard_camera: Trying TCP discovery
[2023-08-04T13:47:02Z INFO  neolink_core::bc_protocol] backyard_camera: TCP Discovery success at 192.168.1.194:9000
[2023-08-04T13:47:02Z INFO  neolink::mqtt::event_cam] backyard_camera: Logging in
[2023-08-04T13:47:07Z WARN  neolink::mqtt::event_cam] Camera thread error: Failed to login to the camera
    
    Caused by:
        deadline has elapsed. Restarting...
```

Coincidentally I just upgraded the firmware from Reolink to deal with some RTSP streaming issues with this camera. Wondering if it's related...

**Comment by MicheleCardamone** [comment]
> Also see  #127

Hi, the problem: "Timed out waiting to send Media Frame" is solved with 0.5.16

**Comment by skylord123** [comment]
> > Also see  #127
> 
> Hi, the problem: "Timed out waiting to send Media Frame" is solved with 0.5.16?

Believe this is still an issue. I am on the latest docker release for neolink and still getting this.

```
[2023-08-09T14:00:41Z INFO  neolink_core::bc_protocol] driveway: Trying TCP discovery
[2023-08-09T14:00:41Z INFO  neolink_core::bc_protocol] driveway: TCP Discovery success at 192.168.1.195:9000
[2023-08-09T14:00:41Z INFO  neolink::rtsp::states::loggedin] driveway: Camera time is already set: 2023-08-09 8:00:41.0 +06:00:00
[2023-08-09T14:00:41Z INFO  neolink::rtsp::states::loggedin] driveway: Camera reports firmware version v2.0.0.1441_19032113_v1.0.0.30
[2023-08-09T14:00:41Z INFO  neolink::rtsp::states::streaming] driveway: Starting video stream Main Stream (Clear)
[2023-08-09T14:00:41Z INFO  neolink::rtsp::states::streaming] driveway: Starting video stream Sub Stream (Fluent)
[2023-08-09T14:00:41Z INFO  neolink::rtsp] driveway: Buffers prepared
[2023-08-09T18:33:43Z INFO  neolink::rtsp] driveway: Join Pause
[2023-08-09T18:33:43Z WARN  neolink::rtsp] driveway: Retryable error: Timed out waiting for new Media Frame
    
    Caused by:
        deadline has elapsed
```

**Comment by MicheleCardamone** [comment]
> > > Also see  #127
> > 
> > 
> > Hi, the problem: "Timed out waiting to send Media Frame" is solved with 0.5.16?
> 
> Believe this is still an issue. I am on the latest docker release for neolink and still getting this. Only happening on one out of three of my cameras. RLC-423ws is the problem child. The RLC-410 cameras are the other ones that are not having this issue.
> 
> Firmware version on camera with issue: v2.0.0.1441_19032113_v1.0.0.30 (last released firmware before being discontinued)
> 
> Neolink log:
> 
> ```
> [2023-08-09T14:00:41Z INFO  neolink_core::bc_protocol] driveway: Trying TCP discovery
> [2023-08-09T14:00:41Z INFO  neolink_core::bc_protocol] driveway: TCP Discovery success at 192.168.1.195:9000
> [2023-08-09T14:00:41Z INFO  neolink::rtsp::states::loggedin] driveway: Camera time is already set: 2023-08-09 8:00:41.0 +06:00:00
> [2023-08-09T14:00:41Z INFO  neolink::rtsp::states::loggedin] driveway: Camera reports firmware version v2.0.0.1441_19032113_v1.0.0.30
> [2023-08-09T14:00:41Z INFO  neolink::rtsp::states::streaming] driveway: Starting video stream Main Stream (Clear)
> [2023-08-09T14:00:41Z INFO  neolink::rtsp::states::streaming] driveway: Starting video stream Sub Stream (Fluent)
> [2023-08-09T14:00:41Z INFO  neolink::rtsp] driveway: Buffers prepared
> [2023-08-09T18:33:43Z INFO  neolink::rtsp] driveway: Join Pause
> [2023-08-09T18:33:43Z WARN  neolink::rtsp] driveway: Retryable error: Timed out waiting for new Media Frame
>     
>     Caused by:
>         deadline has elapsed
> ```
> 
> Once I restart neolink the camera feed starts working again.

I confirm, same problem also with 0.5.17

**Comment by skylord123** [comment]
Actually this seems to happen on the RLC-410 cameras as well. Woke up this morning to 2/3 of the camera feeds broken.

Seems to happen at least once a day to some of my cameras. Reliability isn't great.

```
[2023-08-15T12:44:17Z INFO  neolink_core::bc_protocol] front_yard_door: Trying TCP discovery
[2023-08-15T12:44:17Z INFO  neolink_core::bc_protocol] front_yard_door: TCP Discovery success at 192.168.1.193:9000
[2023-08-15T12:44:17Z INFO  neolink::rtsp::states::loggedin] front_yard_door: Camera time is already set: 2023-08-15 6:44:17.0 +06:00:00
[2023-08-15T12:44:17Z INFO  neolink::rtsp::states::loggedin] front_yard_door: Camera reports firmware version v2.0.0.843_17061500
[2023-08-15T12:44:17Z INFO  neolink::rtsp::states::streaming] front_yard_door: Starting video stream Sub Stream (Fluent)
[2023-08-15T12:44:17Z INFO  neolink::rtsp::states::streaming] front_yard_door: Starting video stream Main Stream (Clear)
[2023-08-15T12:44:25Z WARN  neolink_core::bc_protocol::connection::bcconn] Reaching limit of channel
[2023-08-15T12:44:25Z WARN  neolink_core::bc_protocol::connection::bcconn] Remaining: 0 of 100 message space for 5 (ID: 3)
[2023-08-15T13:52:58Z WARN  neolink_core::bc_protocol::connection::bcconn] Reaching limit of channel
[2023-08-15T13:52:58Z WARN  neolink_core::bc_protocol::connection::bcconn] Remaining: 0 of 100 message space for 4 (ID: 3)
[2023-08-15T13:53:08Z INFO  neolink::rtsp] driveway: Join Pause
[2023-08-15T13:53:08Z WARN  neolink::rtsp] driveway: Retryable error: Timed out waiting to send Media Frame
    
    Caused by:
        deadline has elapsed
[2023-08-15T13:53:08Z INFO  neolink_core::bc_protocol] driveway: Trying TCP discovery
[2023-08-15T13:53:08Z INFO  neolink_core::bc_protocol] driveway: TCP Discovery success at 192.168.1.195:9000
[2023-08-15T13:53:08Z INFO  neolink::rtsp::states::loggedin] driveway: Camera time is already set: 2023-08-15 7:53:08.0 +06:00:00
[2023-08-15T13:53:08Z INFO  neolink::rtsp::states::loggedin] driveway: Camera reports firmware version v2.0.0.1441_19032113_v1.0.0.30
[2023-08-15T13:53:08Z INFO  neolink::rtsp::states::streaming] driveway: Starting video stream Main Stream (Clear)
[2023-08-15T13:53:08Z INFO  neolink::rtsp::states::streaming] driveway: Starting video stream Sub Stream (Fluent)
[2023-08-15T13:53:13Z WARN  neolink_core::bc_protocol::connection::bcconn] Reaching limit of channel
[2023-08-15T13:53:13Z WARN  neolink_core::bc_protocol::connection::bcconn] Remaining: 0 of 100 message space for 4 (ID: 3)
[2023-08-15T15:16:56Z INFO  neolink::rtsp] backyard: Join Pause
[2023-08-15T15:16:56Z WARN  neolink::rtsp] backyard: Retryable error: Timed out waiting for new Media Frame
    
    Caused by:
        deadline has elapsed
```

**Comment by MicheleCardamone** [comment]
> Actually this seems to happen on the RLC-410 cameras as well. Woke up this morning to 2/3 of the camera feeds broken.
> 
> 
> 
> Seems to happen at least once a day to some of my cameras. Reliability isn't great.
> 
> 
> 
> ```
> 
> [2023-08-15T12:44:17Z INFO  neolink_core::bc_protocol] front_yard_door: Trying TCP discovery
> 
> [2023-08-15T12:44:17Z INFO  neolink_core::bc_protocol] front_yard_door: TCP Discovery success at 192.168.1.193:9000
> 
> [2023-08-15T12:44:17Z INFO  neolink::rtsp::states::loggedin] front_yard_door: Camera time is already set: 2023-08-15 6:44:17.0 +06:00:00
> 
> [2023-08-15T12:44:17Z INFO  neolink::rtsp::states::loggedin] front_yard_door: Camera reports firmware version v2.0.0.843_17061500
> 
> [2023-08-15T12:44:17Z INFO  neolink::rtsp::states::streaming] front_yard_door: Starting video stream Sub Stream (Fluent)
> 
> [2023-08-15T12:44:17Z INFO  neolink::rtsp::states::streaming] front_yard_door: Starting video stream Main Stream (Clear)
> 
> [2023-08-15T12:44:25Z WARN  neolink_core::bc_protocol::connection::bcconn] Reaching limit of channel
> 
> [2023-08-15T12:44:25Z WARN  neolink_core::bc_protocol::connection::bcconn] Remaining: 0 of 100 message space for 5 (ID: 3)
> 
> [2023-08-15T13:52:58Z WARN  neolink_core::bc_protocol::connection::bcconn] Reaching limit of channel
> 
> [2023-08-15T13:52:58Z WARN  neolink_core::bc_protocol::connection::bcconn] Remaining: 0 of 100 message space for 4 (ID: 3)
> 
> [2023-08-15T13:53:08Z INFO  neolink::rtsp] driveway: Join Pause
> 
> [2023-08-15T13:53:08Z WARN  neolink::rtsp] driveway: Retryable error: Timed out waiting to send Media Frame
> 
>     
> 
>     Caused by:
> 
>         deadline has elapsed
> 
> [2023-08-15T13:53:08Z INFO  neolink_core::bc_protocol] driveway: Trying TCP discovery
> 
> [2023-08-15T13:53:08Z INFO  neolink_core::bc_protocol] driveway: TCP Discovery success at 192.168.1.195:9000
> 
> [2023-08-15T13:53:08Z INFO  neolink::rtsp::states::loggedin] driveway: Camera time is already set: 2023-08-15 7:53:08.0 +06:00:00
> 
> [2023-08-15T13:53:08Z INFO  neolink::rtsp::states::loggedin] driveway: Camera reports firmware version v2.0.0.1441_19032113_v1.0.0.30
> 
> [2023-08-15T13:53:08Z INFO  neolink::rtsp::states::streaming] driveway: Starting video stream Main Stream (Clear)
> 
> [2023-08-15T13:53:08Z INFO  neolink::rtsp::states::streaming] driveway: Starting video stream Sub Stream (Fluent)
> 
> [2023-08-15T13:53:13Z WARN  neolink_core::bc_protocol::connection::bcconn] Reaching limit of channel
> 
> [2023-08-15T13:53:13Z WARN  neolink_core::bc_protocol::connection::bcconn] Remaining: 0 of 100 message space for 4 (ID: 3)
> 
> [2023-08-15T15:16:56Z INFO  neolink::rtsp] backyard: Join Pause
> 
> [2023-08-15T15:16:56Z WARN  neolink::rtsp] backyard: Retryable error: Timed out waiting for new Media Frame
> 
>     
> 
>     Caused by:
> 
>         deadline has elapsed
> 
> ```
I have same problem but with B800. 

The only way to make it work would be to create a task to close and reopen the process automatically after a few hours. For me the problem occurs about every 4 hours. I am currently using version 0.5.11 to run my BlueIris system. Seems to be fine even if about every hour all the cams lose signal for about 2/3 minutes and then restore themselves. Therefore, there still seem to be several problems today, but the developer has stopped responding to this bug of ours. I'm curious to understand if we have this problem only in a few. 
Mc

**Comment by QuantumEntangledAndy** [comment]
I have something that might help but your issue might be different from the others as it is to do with async thread exhaustion I think.

I should be releasing it later today so try 0.5.18 and report back after it's out

**Comment by MicheleCardamone** [comment]
> I have something that might help but your issue might be different from the others as it is to do with async thread exhaustion I think.
> 
> I should be releasing it later today so try 0.5.18 and report back after it's out 

Hi, I tested 0.5.18 but the same problem occurs. I could not see the "timed out" error because the items displayed are different from the previous version

**Comment by QuantumEntangledAndy** [comment]
Could you maybe check out [this build](https://github.com/QuantumEntangledAndy/neolink/actions/runs/5878595729) it contains a few more optimisations that didn't quite make to 0.5.18 that might help.

**Comment by MicheleCardamone** [comment]
> Could you maybe check out [this build](https://github.com/QuantumEntangledAndy/neolink/actions/runs/5878595729) it contains a few more optimisations that didn't quite make to 0.5.18 that might help. 

i can't download it

**Comment by QuantumEntangledAndy** [comment]
The links are at the bottom of the page I linked under artifacts. Make sure you are logged in to see them.

**Comment by MicheleCardamone** [comment]
> The links are at the bottom of the page I linked under artifacts. Make sure you are logged in to see them.

hi, Same problem also with this bluid.

**Comment by MicheleCardamone** [comment]
I don't know how the others manage to make everything work properly, but it seems that even with version 0.5.11 there are constant problems. In 12 hours of operation 12 "no signal" in blueiris.

**Comment by skylord123** [comment]
> Could you maybe check out [this build](https://github.com/QuantumEntangledAndy/neolink/actions/runs/5878595729) it contains a few more optimisations that didn't quite make to 0.5.18 that might help.

I pulled latest from docker (published 2 days ago) with SHA 75675d782da0 and the problem seems to be resolved for me. No problems for last 30 or so hours. Going to keep monitoring it and will post back if the issue comes back.

**Comment by QuantumEntangledAndy** [comment]
If you have a chance could anyone test [this build](https://github.com/QuantumEntangledAndy/neolink/actions/runs/5909261990) got some improvements to hopefully address this, but not sure since I can't replicate well

**Comment by QuantumEntangledAndy** [comment]
Also for BI please add `spash = false` as discovered in 114

**Comment by MicheleCardamone** [comment]
> If you have a chance could anyone test [this build](https://github.com/QuantumEntangledAndy/neolink/actions/runs/5909261990) got some improvements to hopefully address this, but not sure since I can't replicate well

Hi, tested this build with splash = false. Same problem!

**Comment by skylord123** [comment]
> If you have a chance could anyone test [this build](https://github.com/QuantumEntangledAndy/neolink/actions/runs/5909261990) got some improvements to hopefully address this, but not sure since I can't replicate well

So I thought my issue may have been resolved but no its still happening. I noticed there was a new neolink release last night so I upgraded and the cameras stopped working again after a few hours. 

Dang, was hoping this was fixed but guess it was just random luck that it worked for so long before the issue came back.

**Comment by QuantumEntangledAndy** [comment]
@skylord123 What is your error message. The newer builds I expect to show maybe DroppedConnection error rather than the original `timed out waiting to send media frame`.

I'd like to tackle this one but I need some help finding  out how to replicate so if any one could share their camera and setup it would help

**Comment by MicheleCardamone** [comment]
> @skylord123 What is your error message. The newer builds I expect to show maybe DroppedConnection error rather than the original `timed out waiting to send media frame`.
> 
> 
> 
> I'd like to tackle this one but I need some help finding  out how to replicate so if any one could share their camera and setup it would help

I tested the latest build you posted here in the comments and the error is always “timeout….” I keep wondering if it's just a few people's problem, or if others still use older versions. As I specified in other comments, the version I can use is 0.5.11, which at first glance seems to give no problems, but BI gives "No signal" at least once every 2 hours.
Mc @QuantumEntangledAndy

**Comment by QuantumEntangledAndy** [comment]
Looking at the code around `timed out waiting to send media frame` there is a 3 message buffer. This means that it will pause until there is space in the buffer before sending a frame after 3 messages. 

The other end of the queue is a dedicated thread meant to pass the buffer onto gstreamer. There a LOT of code for this because of how so many clients expect the data to be formatted and so we can handle pausing. If I had to guess the code is getting overloaded here. Maybe the client makes multiple connections which results in processing many buffers.

Could you try this in your config

```toml
[[cameras]]
# Other camera options like UID etc
buffer_size = 0
splash = false
```

That will tell it not to use an internal buffer which will speed up that part of the code but will result in less smooth streams

**Comment by MicheleCardamone** [comment]
@QuantumEntangledAndy 

HI. I tested the latest build you posted here in the comments with the settings buffer size 0 and splash false. The problem occurs as always. I am attaching the config file, the neolink error and the settings in blueiris to try to help you as much as possible. Feel free to ask me for help with what I can do![image](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/f19cc711-7802-43e4-a3bb-fc40dd71b44f)![image](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/00954039-22a1-408a-aff7-d45f2dc27b3b)![image](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/5c600649-4fc1-4847-b1f2-8b7dd5aec542)![image](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/de3ac136-0dee-438c-b09c-900fc96cac93)![image](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/4092fc05-a680-4fb8-88cd-bd2c25f7cc2d)

**Comment by skylord123** [comment]
Using neolink:latest docker container got this issue again today.

It's only happening for the subStream. The main stream is still working for this camera.

Logs:
```
[2023-08-23T17:47:33Z WARN  neolink_core::bc_protocol::connection::bcconn] Reaching limit of channel
[2023-08-23T17:47:33Z WARN  neolink_core::bc_protocol::connection::bcconn] Remaining: 0 of 100 message space for 4 (ID: 3)
[2023-08-23T17:47:41Z INFO  neolink::rtsp] front_yard_door: Join Pause
[2023-08-23T17:47:41Z WARN  neolink::rtsp] front_yard_door: Retryable error: Timed out waiting to send Media Frame
    
    Caused by:
        deadline has elapsed
[2023-08-23T17:47:49Z INFO  neolink_core::bc_protocol] front_yard_door: Trying TCP discovery
[2023-08-23T17:47:49Z INFO  neolink_core::bc_protocol] front_yard_door: TCP Discovery success at 192.168.1.193:9000
[2023-08-23T17:47:49Z INFO  neolink::rtsp::states::loggedin] front_yard_door: Camera time is already set: 2023-08-23 11:47:49.0 +06:00:00
[2023-08-23T17:47:49Z INFO  neolink::rtsp::states::loggedin] front_yard_door: Camera reports firmware version v2.0.0.843_17061500
[2023-08-23T17:47:49Z INFO  neolink::rtsp::states::streaming] front_yard_door: Starting video stream Main Stream (Clear)
[2023-08-23T17:47:49Z INFO  neolink::rtsp::states::streaming] front_yard_door: Starting video stream Sub Stream (Fluent)
[2023-08-23T17:47:57Z WARN  neolink_core::bc_protocol::connection::bcconn] Reaching limit of channel
[2023-08-23T17:47:57Z WARN  neolink_core::bc_protocol::connection::bcconn] Remaining: 0 of 100 message space for 4 (ID: 3)
```

The camera having the issue is `front_yard_door`. `Reaching limit of channel` looks like something that may figure it out.

**Comment by QuantumEntangledAndy** [comment]
Yes I'm actually working on a larger refractor to try and eliminate this but it will take some time and lots of testing.

**Comment by MicheleCardamone** [comment]
> Yes I'm actually working on a larger refractor to try and eliminate this but it will take some time and lots of testing. 

Thank you for the work you are doing. As far as I'm concerned, I'm available to carry out any type of test.
Mc @QuantumEntangledAndy

**Comment by skylord123** [comment]
In the mean time you can wire together something in Node-RED to auto restart Neolink when the streams stop working.

![image](https://github.com/QuantumEntangledAndy/neolink/assets/3412313/a6015a53-dd32-419b-87e7-1803c2393f2e)

Since I am using Xeoma I was able to add the Problem Detector node connected to a HTTP Sender node. When it detects an issue it will call a given URL and pass the problem information. I just setup an endpoint on Node-RED for this and have it use the NR module Dockerode to restart the container.

![image](https://github.com/QuantumEntangledAndy/neolink/assets/3412313/265cd4a2-c455-4875-982e-0d78772be031)

Bonus is it will only restart Neolink if it is already running. That way if you shut it down it wont just start back up unintentionally.

If anyone else wants to use this:
https://gist.github.com/skylord123/434a97ba513287046731b9e07b6e506a

**Comment by MicheleCardamone** [comment]
Hi, Any update? @QuantumEntangledAndy

**Comment by QuantumEntangledAndy** [comment]
On the refactor? It will take over a week, it's quite a lot of work and its only me working on it while also having actual life things too. `Hi, Any update?` and a ping are not helping. If you want to see code pushes it is going onto the `refractor/neo_reactor` branch

**Comment by apedance** [comment]
If you are on Blue Iris you can enable the watchdog and use a simple script like ... 

taskkill /IM neolink.exe /F
C:\Users\name\Neolink\runneolink.cmd

to restart neolink.

**Comment by MicheleCardamone** [comment]
> If you are on Blue Iris you can enable the watchdog and use a simple script like ... 
> 
> 
> 
> taskkill /IM neolink.exe /F
> 
> C:\Users\name\Neolink\runneolink.cmd
> 
> 
> 
> to restart neolink.

it would work, only that every 2/3 hours the system will have holes for a few seconds, which is unacceptable for a video surveillance system. But perhaps it is a better solution than using version 0.5.11 which is the only one that works for me that generates a "No signal" every 2 hours

**Comment by MicheleCardamone** [comment]
@QuantumEntangledAndy 
Hi, how is going with the refactor? Is there anything the community can help you test?

**Comment by QuantumEntangledAndy** [comment]
The main backend is moved over to the new design and the rtsp part is done. Currently working on moving the mqtt into the new model. Last testable build was https://github.com/QuantumEntangledAndy/neolink/actions/runs/6089212723 but this one was before I put in the pause stuff. You can try it if you want. Later builds are all WIP and not at testable points. Be aware that this is all still being revised.

**Comment by MicheleCardamone** [comment]
> The main backend is moved over to the new design and the rtsp part is done. Currently working on moving the mqtt into the new model. Last testable build was https://github.com/QuantumEntangledAndy/neolink/actions/runs/6089212723 but this one was before I put in the pause stuff. You can try it if you want. Later builds are all WIP and not at testable points. Be aware that this is all still being revised.

Hi, first of all thank you for the work you are doing. I tried this version and it doesn't seem to work for me. I always left the same config file but in blue iris I have "no signal" @QuantumEntangledAndy 
MC

**Comment by QuantumEntangledAndy** [comment]
It's usually best to report neolink issues over client issues. I don't own blue iris and I'm sure even if I did no signal seems to be such a generic error it dosent reveal the root cause. What does the log say?

**Comment by skylord123** [comment]
> Last testable build was https://github.com/QuantumEntangledAndy/neolink/actions/runs/6089212723 but this one was before I put in the pause stuff. You can try it if you want.

Is this the same build as tag [refractor-neo_reactor](https://hub.docker.com/layers/quantumentangledandy/neolink/refractor-neo_reactor/images/sha256-a82eaef753647db6e508fb99a736e3acfa1255f46f0304eedb31fbd42e658e44?context=explore) on dockerhub ?

If so I just tried this out and none of my 3 camera streams were coming through. This just kept spamming in the console:

```
[2023-09-11T16:59:33Z INFO  neolink::rtsp] Setting PTS: 9.399s, Runtime: 9.468664s
[2023-09-11T16:59:33Z INFO  neolink::rtsp] Frame recieved with ts: 2790.370008s
[2023-09-11T16:59:33Z INFO  neolink::rtsp] Frame recieved with ts: 2790.370008s
[2023-09-11T16:59:33Z INFO  neolink::rtsp] Setting PTS: 9.549s, Runtime: 9.531507s
[2023-09-11T16:59:33Z INFO  neolink::rtsp] Setting PTS: 9.549s, Runtime: 9.531129s
[2023-09-11T16:59:33Z INFO  neolink::rtsp] Frame recieved with ts: 2790.370008s
[2023-09-11T16:59:33Z INFO  neolink::rtsp] Setting PTS: 9.549s, Runtime: 9.598735s
[2023-09-11T16:59:33Z INFO  neolink::rtsp] Frame recieved with ts: 2790.370008s
[2023-09-11T16:59:33Z INFO  neolink::rtsp] Setting PTS: 9.549s, Runtime: 9.669312s
[2023-09-11T16:59:33Z INFO  neolink::rtsp] Frame recieved with ts: 2790.520008s
[2023-09-11T16:59:33Z INFO  neolink::rtsp] Frame recieved with ts: 2790.520008s
[2023-09-11T16:59:33Z INFO  neolink::rtsp] Setting PTS: 9.699s, Runtime: 9.73394s
[2023-09-11T16:59:33Z INFO  neolink::rtsp] Setting PTS: 9.699s, Runtime: 9.733562s
[2023-09-11T16:59:33Z INFO  neolink::rtsp] Frame recieved with ts: 2790.520008s
[2023-09-11T16:59:33Z INFO  neolink::rtsp] Setting PTS: 9.699s, Runtime: 9.804089s
```

If this is not the same build you mentioned, how do I match up the tag on dockerhub to the github action?



> It's usually best to report neolink issues over client issues.

I tested this tag in VLC as well to remove my DVR software Xeoma from being the problem. Issue happened in VLC as well. Stream couldn't connect.

**Comment by QuantumEntangledAndy** [comment]
That's the right build and the spamming was part of my debug at the time. It is saying the a frame was received and then sent out to the rtsp client.

If it's not working then not much to do bit wait. I was hoping that it will at least connect on that build since I was able to with ffplay but if not I'll comeback and check again once the mqtt bit updated.

**Comment by QuantumEntangledAndy** [comment]
I think the rtsp is ready for testing with the [build here](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6181778205) or `docker pull quantumentangledandy/neolink:refractor-neo_reactor`. Mqtt hasn't been tested properly yet so just test the rtsp please.

**Comment by MicheleCardamone** [comment]
> I think the rtsp is ready for testing with the [build here](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6181778205) or `docker pull quantumentangledandy/neolink:refractor-neo_reactor`. Mqtt hasn't been tested properly yet so just test the rtsp please.

Hi! Tested, it seems to be quite similar to the previous build. I can't see any stream in blueiris, and if it does, it disappears shortly after.
![Screenshot 2023-09-14 161332](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/b0c8c0d7-e1fa-4152-adbd-36c16eccb4e2)

**Comment by QuantumEntangledAndy** [comment]
@MicheleCardamone you have a panic at the end there could you set the rust backtrace variable that it is recommending and try again and show me the log. That way I can know which line it is on

**Comment by QuantumEntangledAndy** [comment]
@skylord123 Everything seems fine on the neolink end. What is your client and how are you connecting? If you set the variable `GST_DEBUG` to `3` it will show the gstreamer logs which will show how far into the connection we get. Also if you use `ffplay` or `ffprobe` to get the stream I can understand error messages of those clients a bit easier since that is what I use for testng

**Comment by MicheleCardamone** [comment]
> @MicheleCardamone you have a panic at the end there could you set the rust backtrace variable that it is recommending and try again and show me the log. That way I can know which line it is on 

Thank you! How can I enable the rust backtrace?

**Comment by QuantumEntangledAndy** [comment]
It's an environmental variable. The method will be different for docker/max/windows/Linux. Which one are you using?

**Comment by MicheleCardamone** [comment]
> It's an environmental variable. The method will be different for docker/max/windows/Linux. Which one are you using?

Windows

**Comment by QuantumEntangledAndy** [comment]
Are you starting neolink using powershell or cmd?

**Comment by QuantumEntangledAndy** [comment]
It would be easier to google this rather than me providing step-by-step until we get there. Environmental variables are quite standard

**Comment by MicheleCardamone** [comment]
> Are you starting neolink using powershell or cmd?

Cmd

**Comment by QuantumEntangledAndy** [comment]
```cmd
set RUST_BACKTRACE=1
```

**Comment by QuantumEntangledAndy** [comment]
Next test build [is here](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6196705538) . It tries to fix the likely suspects or your panic but if you can send the trace back it will help confim that

**Comment by MicheleCardamone** [comment]
> Next test build is here . It tries to fix the likely suspects or your panic but if you can send the trace back it will help confim that

ok, I'll try in a few hours and update you

**Comment by QuantumEntangledAndy** [comment]
Next build is [here](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6205092376)

**Comment by skylord123** [comment]
> Next build is [here](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6205092376)

This build is working, I'll monitor it and see if any issues arise. Thanks!

**Comment by QuantumEntangledAndy** [comment]
Good to hear, this build has a new command `neolink mqtt-rtsp --config=conffile.toml` which starts both mqtt and rtsp.

Theres also a new mqtt topic `neolink/config` which you can publish to and it will update the internal configuration live. That means you can add or remove cameras and also disable/enable streams from the mqtt. Getting all that to work smoothly was one of the reasons the refactor was so long as eveything now watches the config for certain changes and starts/stops things as needed.

It needs a change to the toml to work though, as mqtt is defined globally now rather than individually:

```toml
[mqtt]
  server = "127.0.0.1"
  port = 1883
  credentials = ["username", "password"]

[[cameras]]
# Usual cam stuff
```

**Comment by QuantumEntangledAndy** [comment]
It also:
- completely separate the underlying camera from the tasks it is given to do, so reconnects are simpler and hopefully shorter
- Fixes some bugs during discovery
- Employs low level socket reconnects without full re-login on certain kinds of socket failure
- Uses global shared channels for stream data and motion data (so mqtt and rtsp can both listen to the stream/motion)

**Comment by MicheleCardamone** [comment]
> Next build is [here](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6205092376)

it seems to work better than the previous one, but at least in blueiris, the streams are unusable. Low FPS in both Main and Sub streams
![Screenshot 2023-09-16 165306](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/7a1756e7-2120-43e8-b221-cc4d08d4f028)
![Screenshot 2023-09-16 165531](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/3d0c1d63-3935-494d-bccd-21cca5093e5c)

**Comment by skylord123** [comment]
12 hours without any issues, so far so good. Nice job @QuantumEntangledAndy, appreciate the work you put into this!

> it seems to work better than the previous one, but at least in blueiris, the streams are unusable. Low FPS in both Main and Sub streams

I'm not seeing this. I don't understand from your picture what is the FPS though since there are no column titles. For my cameras I have them set to 20 FPS for the main stream and 10 FPS for the sub stream and I am getting the full FPS through to Xeoma. 
![image](https://github.com/QuantumEntangledAndy/neolink/assets/3412313/0c890bf1-bb7d-45e2-8401-c586598b2106)

Wonder if it has to do with your configuration in Blue Iris. I think you can use `ffprobe` that @QuantumEntangledAndy mentioned earlier to calculate the stream FPS for comparison.

**Comment by MicheleCardamone** [comment]
> 12 hours without any issues, so far so good. Nice job @QuantumEntangledAndy, appreciate the work you put into this!
> 
> > it seems to work better than the previous one, but at least in blueiris, the streams are unusable. Low FPS in both Main and Sub streams
> 
> I'm not seeing this. I don't understand from your picture what is the FPS though since there are no column titles. For my cameras I have them set to 20 FPS for the main stream and 10 FPS for the sub stream and I am getting the full FPS through to Xeoma. ![image](https://user-images.githubusercontent.com/3412313/268473458-0c890bf1-bb7d-45e2-8401-c586598b2106.png)
> 
> Wonder if it has to do with your configuration in Blue Iris. I think you can use `ffprobe` that @QuantumEntangledAndy mentioned earlier to calculate the stream FPS for comparison.

I did an test, I noticed that the problem only occurs on cams with outdated firmware. It's possible? What firmware do you have on your cams? Mine are the B800s
![Firmware](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/fa25d7a4-8701-45d1-9d18-465f3b09e12e)
![Firmware](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/30fe4496-f8d6-4c55-a8c7-ad5cf303b9f5)
![Screenshot 2023-09-17 130316](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/873cb8f2-7490-4195-a6a7-ef18bba40c34)

**Comment by QuantumEntangledAndy** [comment]
How much outdated? Most of the protocol was REd on v2 with the only real addition in the v3 protocol was newer encryption algorithms

**Comment by QuantumEntangledAndy** [comment]
Also

- Model: `Reolink Argus 2E`
  - Firmware: `0616_722_52_478`

- Model: `E1`
- Firmware: `v2.0.0.587_19110800`

**Comment by QuantumEntangledAndy** [comment]
Can you try some basic tests like:
- having ONLY those cameres enabled and no others
- Enabling only substream
- Connecting over UDP (remove addr from the config but keep uid)

**Comment by QuantumEntangledAndy** [comment]
I'm going to release the current work onto master, and maybe close this issue since I think the original is addressed. Could you open a new one about your FPS issues on certain firmwares where we can keep track of things seperatly

**Comment by MicheleCardamone** [comment]
> I'm going to release the current work onto master, and maybe close this issue since I think the original issue has been addressed. Could you open a new issue about your FPS issues on certain firmwares where we can keep track of things seperatly

The firmware on the other cams is the factory one, I had updated the others to the latest one available for B800. I'll take a test; as you suggested, leaving only the 2 updated cams. I also read that in the master release 0.6.0 the buffer size, use smoothing and splash configurations were removed... so I think they should be removed from the config toml file, correct?

**Comment by QuantumEntangledAndy** [comment]
There's no harm to leaving them in the config. They are just ignored.
