### ISSUE TITLE
Dailey 2 minutes in rtsp

### ISSUE THREAD

**Issue by Roei639** [QuantumEntangledAndy/neolink#209]
Hello,
After some time the broadcast time on rtsp is 2 minutes behind the reolink app

version: Neolink Release 0.6.3-rc.1
camera: reolink lumus

Thank you

**Comment by lloydsmart** [comment]
Same issue here. Using a Reolink E1 with the Docker version of the app.

**Comment by kyle170** [comment]
Chiming in, same issues, Large delay with using the (`QuantumEntangledAndy/neolink:latest`) docker image but when using the deprecated image (`thirtythreeforty/neolink:latest`) 

Theres also a closed bug here (https://github.com/QuantumEntangledAndy/neolink/issues/132) but I dont think its actually resolved as I am still experiencing it even after adding `buffer_size = 0` to my config

**Comment by Dexdiman** [comment]
I'm having the same issue with all of my E1's.  Running the latest release in a docker and seeing the 1-2 min delay on the cameras. This doesn't appear to happen running it as an exe on my Blue Iris server, but I much prefer docker.

**Comment by JulesAU** [comment]
Also saw 15-20s of latency until I downgraded to 0.6.1.  Reolink Lumus v2.

**Comment by QuantumEntangledAndy** [comment]
I think I have this fixed now but need to finish testing it. The history buffer was growing infinitely if the camera was not sending correctly timestamped frames

**Comment by Roei639** [comment]
> I think I have this fixed now but need to finish testing it. The history buffer was growing infinitely if the camera was not sending correctly timestamped frames

Is the problem found?

**Comment by QuantumEntangledAndy** [comment]
Yeah should already been fixed in master.

**Comment by DAM21** [comment]
I tried the current master and am still experiencing a long delay. It was over a minute and a half earlier today. Camera is a Lumus upgraded 2K. I downgraded to 0.6.1, as others mentioned, and I'm only seeing about 5 sec delay.

**Comment by kyle170** [comment]
Chiming in also, current master has long delay, downgrading to v0.6.1 fixes issue. @QuantumEntangledAndy doesn't seem like this issue has been fixed.

**Comment by gordnhoo** [comment]
Having the same issue reverting to v0.6.1 also reduced the delay like @kyle170

**Comment by QuantumEntangledAndy** [comment]
I see well I'll have another look when I have the time but I am working on other projects and the day job for awhile.

**Comment by cmcm711** [comment]
Appreciate all you do for this project! Wanted to chime in indicating I am also experiencing this issue with a Reolink Lumus camera. Using 0.6.3 starts out with a 20ish second delay, growing to multiple minutes after an hour or two. Using 0.6.1 fixes the issue, giving only a ~3 second delay (acceptable) that never grows.

**Comment by stintel** [comment]
I too am experiencing this bug. I am having an attempt at fixing it in my fork. As master is completely broken for me, I have started from the v0.6.3.rc.2 tag. 

https://github.com/stintel/neolink/tree/release/v0.6.3

**Comment by vertoforce** [comment]
Fixed in [commit](https://github.com/vertoforce/neolink/commit/8d0c3b0) in my fork. The delay grows because the appsrc drops the newest frame under pressure, so late frames queue and the stream never catches up. Same bug as #378, #233, #132.

<details>
<summary>Details (mechanism, numbers; written up with AI help)</summary>

The 2024 history-buffer change did not settle this. Four people retested on master afterwards and still saw the delay grow. Making the video appsrc leaky-downstream drops the oldest frame instead, so a slow consumer costs frames rather than seconds.

A second fault has the same symptom. The microsecond timestamp counter was 32-bit and wrapped every 71.58 minutes, fixed in [commit](https://github.com/vertoforce/neolink/commit/9a66956).

stintel's branch is a different starting point from mine. I cannot tell from this thread which of the two faults applies to each reporter here.

</details>
